export interface AllProject {
  status_pembayaran_id?: string | number | readonly string[] | undefined;
  nama_status_pembayaran?: string;
  tanggalStatus?: number | string;
  catatan?: string;
  id_project?: number;
  nama_perusahaan?: string;
  nama_sales_or_crr?: string;
  standar?: [];
  akreditasi?: number;
  tahapan?: string;
  tgl_apl_form_or_request?: string;
  note_tgl_apl_form_or_request?: string;
  tgl_review_penugasan_st_satu?: string;
  note_tgl_review_penugasan_st_satu?: string | undefined;
  tgl_review_penugasan_st_dua?: string;
  note_tgl_review_penugasan_st_dua?: string;
  tgl_pengiriman_notif_st_satu?: string;
  note_tgl_pengiriman_notif_st_satu?: string | undefined;
  tgl_pengiriman_notif_st_dua?: string;
  note_tgl_pengiriman_notif_st_dua?: string | undefined;
  tgl_persetujuan_notif_st_satu?: string;
  note_tgl_persetujuan_notif_st_satu?: string | undefined;
  tgl_persetujuan_notif_st_dua?: string;
  note_tgl_persetujuan_notif_st_dua?: string | undefined;
  tgl_pengiriman_audit_plan_st_satu?: string;
  note_tgl_pengiriman_audit_plan_st_satu?: string | undefined;
  tgl_pengiriman_audit_plan_st_dua?: string;
  note_tgl_pengiriman_audit_plan_st_dua?: string | undefined;
  tgl_pelaksanaan_audit_st_satu?: string;
  note_tgl_pelaksanaan_audit_st_satu?: string | undefined;
  tgl_pelaksanaan_audit_st_dua?: string;
  note_tgl_pelaksanaan_audit_st_dua?: string | undefined;
  tgl_penyelesaian_capa_st_satu?: string;
  note_tgl_penyelesaian_capa_st_satu?: string | undefined;
  tgl_penyelesaian_capa_st_dua?: string;
  note_tgl_penyelesaian_capa_st_dua?: string | undefined;
  tgl_pengiriman_sertifikat?: string;
  note_tgl_pengiriman_sertifikat?: string | undefined;
  tgl_persetujuan_draft_sertifikat?: string;
  note_tgl_persetujuan_draft_sertifikat?: string | undefined;
  tgl_pengajuan_ke_kan?: string;
  note_tgl_pengajuan_ke_kan?: string | undefined;
  tgl_persetujuan_kan?: string;
  note_tgl_persetujuan_kan?: string | undefined;
  status_pembayaran?: number | undefined;
  note_status_pembayaran?: string | undefined;
  tgl_kirim_sertifikat?: string;
  note_tgl_kirim_sertifikat?: string | undefined;
  status_data?: number;
  create_date?: string;
  cycle_date?: string;
  create_user?: string | undefined;
  cycle_user?: number;
  nama_akreditasi?: string;
  nama_tahapan?: string;
}

export interface MenuProject {
  status_pembayaran_id: string | number | readonly string[] | undefined;
  nama_status_pembayaran: string;
  id_standar: string | number | readonly string[] | undefined;
  nama_standar: string;
  id_tahapan: string | number | readonly string[] | undefined;
  nama_tahapan: string;
  id_akreditasi: number;
  nama_akreditasi: string;
  status: number;
  id: string;
  name: string;
}
